server:
  port: 5003

spring:
  application:
    name: location-service

  datasource:
    url: jdbc:mysql://localhost:3306/yt_airline_location_db
    username: root
    password: "Panha@168$"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true